---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: __SERVICE_NAME__-dbmigration
  namespace: flux-config
  labels:
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  image: ${APPLICATION_ACR_NAME}.azurecr.io/image/__SERVICE_NAME__-dbmigration
  interval: 60m0s
  provider: azure
