apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: __SERVICE_NAME__-pre-deploy
  namespace: flux-config
  labels:
    backstage.io/kubernetes-id: __SERVICE_NAME__
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  dependsOn:
    - name: __SERVICE_NAME__-infra
      namespace: flux-config
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config
  path: ./services/__PROGRAMME_NAME__/__TEAM_NAME__/__SERVICE_NAME__/pre-deploy/${ENVIRONMENT}/${ENVIRONMENT_ID}
  interval: 5m
  timeout: 3m
  prune: true
  wait: true
  force: true
  postBuild:
    substitute:
      SHARED_POSTGRES_SERVER_01: "${SHARED_POSTGRES_SERVER_01}"
      SERVICE_NAME: "__SERVICE_NAME__"
      TEAM_NAMESPACE: ${TEAM_NAMESPACE}
      TEAM_NAME: ${TEAM_NAME}
      PLATFORM_DB_ADMIN: ${PLATFORM_DB_ADMIN}
      POSTGRES_DB_NAME: "__POSTGRES_DB__"
      POSTGRES_PORT: '"5432"'
      POSTGRES_SCHEMA_NAME: "public"
    substituteFrom:
      - kind: ConfigMap
        name: adp-platform-vars
      - kind: ConfigMap
        name: "__SERVICE_NAME__-mi-credential"