apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: __TEAM_NAME__-base
  namespace: flux-config
  labels:
    backstage.io/kubernetes-team: __TEAM_NAME__
spec:
  sourceRef:
    kind: GitRepository
    name: services-repository
    namespace: flux-config
  interval: 3m
  timeout: 2m
  prune: true
  path: ./services/__PROGRAMME_NAME__/__TEAM_NAME__/${ENVIRONMENT}/${ENVIRONMENT_ID}
  postBuild:
    substitute:
      TEAM_NAMESPACE: "__TEAM_NAME__"
      TEAM_NAME: "__TEAM_NAME__-team"
      TEAM_RG: "${SERVICES_INFRA_RG}-__TEAM_NAME__"
      APPCONFIG_MI_CLIENTID: ${APPCONFIG_MI_CLIENTID}
      APPCONFIG_NAME: ${APPCONFIG_NAME}
      SERVICE_CODE: "__SERVICE_CODE__"
      PLATFORM_DB_ADMIN: "adp-platform-db-aad-admin"
      TEAM_CPU_QUOTA: "__TEAM_CPU_QUOTA__"
      TEAM_MEMORY_QUOTA: "__TEAM_MEMORY_QUOTA__"
      TEAM_PODS_QUOTA: "__TEAM_PODS_QUOTA__"
      CONTAINER_MAX_CPU: "__CONTAINER_MAX_CPU__"
      CONTAINER_MAX_MEMORY: "__CONTAINER_MAX_MEMORY__"
    substituteFrom:
      - kind: ConfigMap
        name: __TEAM_NAME__-mi-credential
        optional: true
      - kind: ConfigMap
        name: adp-platform-vars
